### ISSUE TITLE
Reporting problems with scripts

### ISSUE THREAD

**Issue by RandomClunk** [RandomClunk/gats.io#2]
**If you are reporting a problem with the scripts, include the following details.**

1. The script that has the problem.
2. The gats version when you used the script.
2. The problem.
3. Your browser and browser version.
4. What you already tried.
5. How you used the script. **example: in console or tampermonkey.**

**Comment by nightwailker** [comment]
it wont work

**Comment by RandomClunk** [comment]
> it wont work

Please open a new issue and include the mentioned details.

Closing this as its only meant to guide people.
