### ISSUE TITLE
Update debugger bypass for version 2.0.3

### ISSUE THREAD

**Issue by rpxs** [RandomClunk/gats.io#3]

**Comment by rpxs** [comment]
Version has just been changed to 2.0.4

**Comment by Scripter35** [comment]
pls fix the dubugger bypass and the hack.js it was working it said "Hacks Activated" but when I hold Shift it doesnt do the aimbot it doesnt place my mouse cursor on the player its just staying still while I have to control.

**Comment by rpxs** [comment]
Just fix it, you're a scripter aren't you?

**Comment by RandomClunk** [comment]
@rpxs @Scripter35 The script has been updated for version 2.0.4 [#ec64556](https://github.com/RandomClunk/gats.io/commit/ec645563d35e56d797772a2601acc7b1ff637d33) [debugger-bypass.user.js](https://github.com/RandomClunk/gats.io/blob/main/patches/debugger-bypass.user.js)
