### ISSUE TITLE
The hacks are fake

### ISSUE THREAD

**Issue by AurangAsif** [RandomClunk/gats.io#5]
1. The script that has the problem.
[patches/hack.js](https://github.com/RandomClunk/gats.io/blob/main/patches/hack.js) and [patches/multiboxing.js](https://github.com/RandomClunk/gats.io/blob/main/patches/multiboxing.js)
2. The gats version when you used the script.
Last Updated
23 February 2021
3. The problem.
They are fake. I checked and they do nothing besides open fake popups. Please put real hacks in place of them.
4. Your browser and browser version.
Chrome 88.0.4324.182
5. What you already tried.
Using the scripts and checking for errors
6. How you used the script. example: in console or tampermonkey.
Console

**Comment by RandomClunk** [comment]
The latest Chrome version 92.1.4354.140 is required for the mentioned scripts to work.
