### ISSUE TITLE
Clone hack issues

### ISSUE THREAD

**Issue by Falcon0118** [RandomClunk/gats.io#6]
It doesn't seem to work for me on gats.
I paste it into console and do what Random Clunk told me to, but it didn't seem to work.
After I press enter to activate the code, pop ups appear, I clear them, and then close the console, but then it reloads the page and fails. Random Clunk told me to open an issue to receive help, so that's exactly what I'm doing. By the way, if you'd like to help me, please use very easy words, because I don't code at all, so yea... Anyways, appreciate it.

**Comment by RandomClunk** [comment]
Please include the details as described in #2

**Comment by Falcon0118** [comment]
If you are reporting a problem with the scripts, include the following details.

The script that has the problem is multiboxing.js

The gats version when you used the script.
   - I'm not sure what the version is. I've asked around in-game on how to find the version number, but nobody seems to know. I used to see it on the bottom left hand corner on the home screen, but now it is gone. So...yea...but all I can tell you is that it updated on February 23, 2021

The problem.
   - When I paste in console and close the pop ups, and then close the console, it forces the page to reload, causing the hack to be erased.
  
Your browser and browser version.
   - Chrome; Version 89.0.4389.90

What you already tried.
   - Pasting it into console
   - Closing everything really fast
   - I've  tried this like 20 times, still not working.

How you used the script. example: in console or tampermonkey.
   - In console

**Comment by RandomClunk** [comment]
![image](https://user-images.githubusercontent.com/74115138/111854290-cb59f480-88f4-11eb-80dd-b6d671de7e3b.png)
This is the latest version of Chrome, which is required for the script to function. Try updating Chrome and use the script.

**Comment by Falcon0118** [comment]
How do I update chrome to that version?
![image](https://user-images.githubusercontent.com/80932236/111857932-39e98300-88f2-11eb-9f99-ccb1cbb2db58.png)

**Comment by RandomClunk** [comment]
You can download the latest version from [here](https://www.google.com/intl/en_ca/chrome/). You don't need the Enterprise build but version 97+ and 256bit is required. Stability doesn't matter either.

**Comment by Falcon0118** [comment]
If i click download, it downloads a 64-bit version...Now i'm confused...
![image](https://user-images.githubusercontent.com/80932236/112029577-a208b680-8af6-11eb-8704-a942556f6a8c.png)

**Comment by RandomClunk** [comment]
Yes, you need to download the 64-bit version. After 4 days, it will auto upgrade itself to the 256-bit version (4 * 64 = 256).

**Comment by Scripter35** [comment]
> It doesn't seem to work for me on gats.
> I paste it into console and do what Random Clunk told me to, but it didn't seem to work.
> After I press enter to activate the code, pop ups appear, I clear them, and then close the console, but then it reloads the page and fails. Random Clunk told me to open an issue to receive help, so that's exactly what I'm doing. By the way, if you'd like to help me, please use very easy words, because I don't code at all, so yea... Anyways, appreciate it.

Same
